on run
	activate
	«event sysodlog» "In Finder, right-click a project folder and choose Quick Actions > Open in Codex Project (or Services > Open in Codex Project). Open the project with its Codex identity, or set, change, and remove its folder configuration." given «class appr»:"Codex Project", «class btns»:{"OK"}, «class dflt»:"OK"
end run

on open selectedItems
	activate
	repeat with selectedItem in selectedItems
		set folderPath to «class psxp» of selectedItem
		try
			set launcherPath to «class psxp» of («event sysorpth» "codex-home")
			set hasContext to my fileExists(folderPath & "/.envrc")
			set projectAction to my chooseProjectAction(hasContext)

			if projectAction is not false then
				if projectAction is "Open with current Codex context" then
					my launchProject(launcherPath, folderPath)
				else if projectAction is "Set up a Codex identity for this folder…" or projectAction is "Set or change Codex identity…" then
					if my configureProject(launcherPath, folderPath, hasContext) then
						my launchProject(launcherPath, folderPath)
					end if
				else if projectAction is "Remove Codex context from this folder…" then
					my removeProjectContext(launcherPath, folderPath)
				end if
			end if
		on error errorMessage number errorNumber
			if errorNumber is not -128 then
				«event sysodisA» "Codex Project could not complete this action" given «class mesS»:errorMessage
			end if
		end try
	end repeat
end open

on chooseProjectAction(hasContext)
	if not hasContext then return "Set up a Codex identity for this folder…"

	set actionItems to {"Open with current Codex context", "Set or change Codex identity…", "Remove Codex context from this folder…"}
	set actionChoice to «event gtqpchlt» actionItems given «class appr»:"Codex Project", «class prmp»:"This folder has a .envrc. What would you like to do?", «class inSL»:{"Open with current Codex context"}, «class okbt»:"Continue", «class cnbt»:"Cancel", «class mlsl»:false, «class empL»:false
	if actionChoice is false then return false
	return item 1 of actionChoice
end chooseProjectAction

on configureProject(launcherPath, folderPath, replacingContext)
	set identitiesText to my runCommand({launcherPath, "list", "--names"})
	if identitiesText is "" then
		«event sysodisA» "No configured Codex identities were found" given «class mesS»:"Create or repair an identity with codex-home, then open this folder with Codex Project again."
		return false
	end if

	set identityChoice to «event gtqpchlt» (paragraphs of identitiesText) given «class appr»:"Choose Codex Identity", «class prmp»:"Choose the identity for this folder:", «class inSL»:{}, «class okbt»:"Continue", «class cnbt»:"Cancel", «class mlsl»:false, «class empL»:false
	if identityChoice is false then return false
	set identityName to item 1 of identityChoice

	if replacingContext then
		set confirmationText to "Replace this folder’s generated Codex context with identity “" & identityName & "”? Approval for the current .envrc will be revoked. Only unmodified, untracked regular files generated by codex-home can be replaced."
		set setupCommandName to "project-change"
		set confirmationButton to "Change"
		set defaultChoice to "Cancel"
	else
		set confirmationText to "Create a machine-local .envrc and a folder-named VS Code workspace for identity “" & identityName & "”? Existing files will not be overwritten."
		set setupCommandName to "project"
		set confirmationButton to "Set Up"
		set defaultChoice to "Set Up"
	end if

	set setupChoice to «event sysodlog» confirmationText given «class appr»:"Configure Codex Project?", «class btns»:{"Cancel", confirmationButton}, «class dflt»:defaultChoice, «class cbtn»:"Cancel"
	if «class bhit» of setupChoice is not confirmationButton then return false

	my runCommand({launcherPath, setupCommandName, identityName, folderPath})

	if not my reviewAndApproveProject(launcherPath, folderPath, identityName) then
		«event sysodlog» "The project files are configured, but .envrc is not approved. Review and approve it with direnv before choosing Open with current Codex context." given «class appr»:"Setup Paused", «class btns»:{"OK"}, «class dflt»:"OK"
		return false
	end if
	return true
end configureProject

on reviewAndApproveProject(launcherPath, folderPath, identityName)
	set projectName to «event sysoexec» "/usr/bin/basename " & quoted form of folderPath
	set hasReviewed to false

	repeat
		if hasReviewed then
			set reviewMessage to "Review completed." & return & return & "Project: " & projectName & return & "Identity: " & identityName & return & "File: .envrc" & return & return & "Approve & Open lets direnv execute this file and opens VS Code with this identity. Credentials remain in the identity home; they are not copied into the project."
			set reviewButtons to {"Leave Unapproved", "Review Again", "Approve & Open"}
			set defaultButtonName to "Approve & Open"
		else
			set reviewMessage to "Review the generated environment before approving it." & return & return & "Project: " & projectName & return & "Identity: " & identityName & return & "File: .envrc" & return & return & "Review in VS Code opens a read-only copy of .envrc with shell syntax highlighting. Close that review window to return here."
			set reviewButtons to {"Leave Unapproved", "Review in VS Code"}
			set defaultButtonName to "Review in VS Code"
		end if

		set reviewChoice to «event sysodlog» reviewMessage given «class appr»:"Review Codex Environment", «class btns»:reviewButtons, «class dflt»:defaultButtonName
		set chosenButton to «class bhit» of reviewChoice
		if chosenButton is "Leave Unapproved" then return false

		if chosenButton is "Review in VS Code" or chosenButton is "Review Again" then
			my runCommand({launcherPath, "project-review", folderPath})
			set hasReviewed to true
		else if chosenButton is "Approve & Open" then
			my runCommand({"direnv", "allow", folderPath})
			return true
		end if
	end repeat
end reviewAndApproveProject

on removeProjectContext(launcherPath, folderPath)
	set removeChoice to «event sysodlog» "Remove this folder’s generated, untracked .envrc and Codex workspace? Its direnv approval and local Git-exclude entries will also be removed. Identities, credentials, .codex, and unrelated VS Code settings will remain." given «class appr»:"Remove Codex Context?", «class btns»:{"Cancel", "Remove"}, «class dflt»:"Cancel", «class cbtn»:"Cancel"
	if «class bhit» of removeChoice is not "Remove" then return false

	my runCommand({launcherPath, "project-reset", folderPath})
	«event sysodlog» "The generated Codex context was removed from this folder. Identity homes and credentials were not changed." given «class appr»:"Codex Context Removed", «class btns»:{"OK"}, «class dflt»:"OK"
	return true
end removeProjectContext

on launchProject(launcherPath, folderPath)
	my runCommand({"/usr/bin/env", "CODEX_VSCODE_DOCK_LABEL=1", launcherPath, "vscode-project", folderPath})
end launchProject

on runCommand(commandArguments)
	set shellCommand to ""
	repeat with commandArgument in commandArguments
		set shellCommand to shellCommand & " " & quoted form of (commandArgument as text)
	end repeat
	return «event sysoexec» "/bin/zsh -lc " & quoted form of shellCommand
end runCommand

on fileExists(filePath)
	try
		set quotedPath to quoted form of filePath
		«event sysoexec» "/bin/test -e " & quotedPath & " || /bin/test -L " & quotedPath
		return true
	on error errorMessage number errorNumber
		if errorNumber is 1 then return false
		error errorMessage number errorNumber
	end try
end fileExists
